#!/bin/bash

########################################################
##### USE THIS FILE IS YOU LAUNCHED AMAZON LINUX 2 #####
########################################################

# Download app
cd /home/ec2-user
wget https://github.com/simplesteph/ec2-masterclass-sampleapp/releases/download/v1.0/ec2-masterclass-sample-app.jar

# Test the app
java -Xmx700m -jar ec2-masterclass-sample-app.jar

# System D type of Configuration for Linux 2
sudo bash -c 'cat << \EOF > /etc/systemd/system/vishalvitaapplication.service
[Unit]
Description=EC2 VV App
After=network.target

[Service]
ExecStart=/usr/bin/java -jar /home/ec2-user/VV-10.10.2020.jar
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF'

# apply across reboots
sudo systemctl enable vvapplication.service # enable on boot
sudo systemctl start vvapplication.service  # start now
